volumes:
  orderer1.layer1.chains:
  peer1.layer1.chains:
  peer2.layer1.chains:
  peer3.layer1.chains:
  peer4.layer1.chains:
  peer5.layer1.chains:
  peer6.layer1.chains:
  peer7.layer1.chains:
  peer8.layer1.chains:


networks:
  chains:
    name: chains


services:
  orderer1.layer1.chains:
    container_name: orderer1.layer1.chains
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7001
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9201
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer1.layer1.chains:9101
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../chains/ordererOrganizations/layer1.chains/orderers/orderer1.layer1.chains/msp:/var/hyperledger/orderer/msp
      - ../chains/ordererOrganizations/layer1.chains/orderers/orderer1.layer1.chains/tls:/var/hyperledger/orderer/tls
      - orderer1.layer1.chains:/var/hyperledger/production/orderer
    ports:
      - 7001:7001
      - 9101:9101
      - 9201:9201
    networks:
      - chains

  peer1.layer1.chains:
    container_name: peer1.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.layer1.chains
      - CORE_PEER_ADDRESS=peer1.layer1.chains:6001
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6001
      - CORE_PEER_CHAINCODEADDRESS=peer1.layer1.chains:6101
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6101
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.layer1.chains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.layer1.chains:6001
      - CORE_PEER_LOCALMSPID=layer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.layer1.chains:9001
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1layer1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../chains/peerOrganizations/layer1.chains/peers/peer1.layer1.chains:/etc/hyperledger/fabric
      - peer1.layer1.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6001:6001
      - 9001:9001
    networks:
      - chains

  peer2.layer1.chains:
    container_name: peer2.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer2.layer1.chains
      - CORE_PEER_ADDRESS=peer2.layer1.chains:6002
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6002
      - CORE_PEER_CHAINCODEADDRESS=peer2.layer1.chains:6102
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6102
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.layer1.chains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.layer1.chains:6002
      - CORE_PEER_LOCALMSPID=layer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer2.layer1.chains:9002
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer2layer1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../chains/peerOrganizations/layer1.chains/peers/peer2.layer1.chains:/etc/hyperledger/fabric
      - peer2.layer1.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6002:6002
      - 9002:9002
    networks:
      - chains

  peer3.layer1.chains:
    container_name: peer3.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer3.layer1.chains
      - CORE_PEER_ADDRESS=peer3.layer1.chains:6003
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6003
      - CORE_PEER_CHAINCODEADDRESS=peer3.layer1.chains:6103
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6103
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.layer1.chains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.layer1.chains:6003
      - CORE_PEER_LOCALMSPID=layer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer3.layer1.chains:9003
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer3layer1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../chains/peerOrganizations/layer1.chains/peers/peer3.layer1.chains:/etc/hyperledger/fabric
      - peer3.layer1.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6003:6003
      - 9003:9003
    networks:
      - chains

  peer4.layer1.chains:
    container_name: peer4.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer4.layer1.chains
      - CORE_PEER_ADDRESS=peer4.layer1.chains:6004
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6004
      - CORE_PEER_CHAINCODEADDRESS=peer4.layer1.chains:6104
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6104
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.layer1.chains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.layer1.chains:6004
      - CORE_PEER_LOCALMSPID=layer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer4.layer1.chains:9004
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer4layer1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../chains/peerOrganizations/layer1.chains/peers/peer4.layer1.chains:/etc/hyperledger/fabric
      - peer4.layer1.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6004:6004
      - 9004:9004
    networks:
      - chains

  peer5.layer1.chains:
    container_name: peer5.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer5.layer1.chains
      - CORE_PEER_ADDRESS=peer5.layer1.chains:6005
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6005
      - CORE_PEER_CHAINCODEADDRESS=peer5.layer1.chains:6105
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6105
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.layer1.chains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5.layer1.chains:6005
      - CORE_PEER_LOCALMSPID=layer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer5.layer1.chains:9005
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer5layer1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../chains/peerOrganizations/layer1.chains/peers/peer5.layer1.chains:/etc/hyperledger/fabric
      - peer5.layer1.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6005:6005
      - 9005:9005
    networks:
      - chains

  peer6.layer1.chains:
    container_name: peer6.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer6.layer1.chains
      - CORE_PEER_ADDRESS=peer6.layer1.chains:6006
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6006
      - CORE_PEER_CHAINCODEADDRESS=peer6.layer1.chains:6106
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6106
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.layer1.chains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer6.layer1.chains:6006
      - CORE_PEER_LOCALMSPID=layer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer6.layer1.chains:9006
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer6layer1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../chains/peerOrganizations/layer1.chains/peers/peer6.layer1.chains:/etc/hyperledger/fabric
      - peer6.layer1.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6006:6006
      - 9006:9006
    networks:
      - chains

  peer7.layer1.chains:
    container_name: peer7.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer7.layer1.chains
      - CORE_PEER_ADDRESS=peer7.layer1.chains:6007
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6007
      - CORE_PEER_CHAINCODEADDRESS=peer7.layer1.chains:6107
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6107
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.layer1.chains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer7.layer1.chains:6007
      - CORE_PEER_LOCALMSPID=layer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer7.layer1.chains:9007
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer7layer1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../chains/peerOrganizations/layer1.chains/peers/peer7.layer1.chains:/etc/hyperledger/fabric
      - peer7.layer1.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6007:6007
      - 9007:9007
    networks:
      - chains

  peer8.layer1.chains:
    container_name: peer8.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer8.layer1.chains
      - CORE_PEER_ADDRESS=peer8.layer1.chains:6008
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6008
      - CORE_PEER_CHAINCODEADDRESS=peer8.layer1.chains:6108
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6108
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.layer1.chains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer8.layer1.chains:6008
      - CORE_PEER_LOCALMSPID=layer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer8.layer1.chains:9008
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer8layer1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../chains/peerOrganizations/layer1.chains/peers/peer8.layer1.chains:/etc/hyperledger/fabric
      - peer8.layer1.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6008:6008
      - 9008:9008
    networks:
      - chains
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../../cert:/opt/gopath/src/github.com/hyperledger/fabric/peer/../cert/
    depends_on:
      - peer1.layer1.chains
      - peer2.layer1.chains
      - peer3.layer1.chains
      - peer4.layer1.chains
      - peer5.layer1.chains
      - peer6.layer1.chains
      - peer7.layer1.chains
      - peer8.layer1.chains
    networks:
      - chains