version: '3.7'
services:
  peer1.layer1.chains:
    container_name: peer1.layer1.chains
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=chains
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock

  peer2.layer1.chains:
    container_name: peer2.layer1.chains 
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=chains
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock

  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg